server:
  port: 2001
spring:
  datasource:
    url:   jdbc:mysql://10.147.20.74:3306/building?characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    #url:   jdbc:mysql://112.74.41.41:3306/building?characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    #url jdbc:mysql://10.168.200.65:3306/building?characterEncoding=UTF-8
    username: zlx
    password: z423z423
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource

  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
  gson:
    date-format: YYYY-MM-dd HH:mm:ss
mybatis-plus:
  #  mapper-locations: classpath:xml/*.xml
  #type-handlers-package: com.qrs.admin.onenet.handler.type
  mapper-locations: classpath*:/mapper/*/*Mapper.xml
  type-aliases-package: com.flushbonading.pojo
  configuration:
    # 自动驼峰命名
    map-underscore-to-camel-case: false